### ISSUE TITLE
Pin Descriptions in Examples Potentially Wrong

### ISSUE THREAD

**Issue by Grippy98** [paulvha/AD57xx#2]
https://github.com/paulvha/AD57xx/blob/master/examples/AD57_man_bipolar/AD57_man_bipolar.ino

In examples such as these, Pin 15 is listed as + pole 9V, where as the datasheet lists pin 24 as AVdd (Positive Analog Supply) and pin 1 as AVss (Negative Analog Supply)

The comments also list the AVdd Pin as being connected to +5V.

I believe these need changing.

**Comment by paulvha** [comment]
Thank Grippy98 for the feedback. 
Actually the sketch is correct. With connecting the + of the 9V to GND and the - to pin1, we generate a negative voltage of 9V on AVss (pin 1) and thus enable a bipolar output range between -9V and +5V on the AVdd (pin 24). 

In other setup pin 1 (AVss) is connected to GND and AVdd (pin24) to +5V, the output range is between 0V and 5V
